# Add your own tasks in files placed in lib/take,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

task default: %w[hello]
 
task :hello do
  puts "Hello world!"
end
